allowBuilds:
  "@playwright/browser-chromium": true
  esbuild: true
  workerd: true

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.3
  vite-plus: 0.3.3

overrides:
  vite: "catalog:"

patchedDependencies:
  "@shadcn/registry@0.1.0": patches/@shadcn__registry@0.1.0.patch

peerDependencyRules:
  allowAny: [vite]
  allowedVersions:
    vite: "*"

update:
  ignoreDeps: [vite, vite-plus]
